Improve gene glyph display and performance (#523)
* Remove unused unserializable state

Fixes the following error when opening the TranscriptDetailsWidget:
DataCloneError: Failed to execute 'put' on 'IDBObjectStore': [object
Object] could not be cloned.

* Pre-load commonly checked equivalent types

* apollo track updates

* feature layout improvements and loading indicator

* clean up old features

* fixes

* fixes

* add circular loader

* Move loading circle a bit to avoid scrollbar


skip-checks:true

---------

Co-authored-by: Shashank Budhanuru Ramaraju <shashank.b.r.gowda45587@gmail.com>