Add startup docs to website (#496)
* Add email form to website

* Add new items to homepage

* Add "Try it out" guide

* Move CLI docs into admin section

* Start docker compose docs

* Several typo fixes an improvements

* Add more docker and login docs

* Fix broken links

* Have demo link open small local GFF3

* Edit how to add evidence tracks jbrowse; Edit header (#495)

Do not cd to `jbrowse_data` otherwise you get:

```
apollo jbrowse get-config
    Error: Configuration file "/root/.config/apollo-cli/config.yml" does not
    exist. Please run "apollo config" first
```

Write config.json to `data/` so docker can see it otherwise you get:

```
apollo jbrowse set-config config.json
 ›   Error: File config.json does not exist
```

---

Docs header merged to be more consistent with text.

* Add images to quick-start annotation guide (#494)

* Start adding images

* Increase figure size

* Add further images

* Use markdown images for Docusaurus

---------

Co-authored-by: Garrett Stevens <stevens.garrett.j@gmail.com>

* Remove ROOT_USER_NAME from docs

* Add contact page

* Add blog post

* Typo; add note about using CLI

* Fix config; use latest Apollo and JBrowse versions

* Clarify deployment example docs

* More updates to docker compose deployment

* Fix env file typo

---------

Co-authored-by: Dario Beraldi <dario.beraldi@gmail.com>